### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './finetune_demo/output/checkpoint-3000'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by Ch180907** [holk-h/CyberFriend#1]
部署完LLM模型后，运行出现下面错误：
Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\nonebot\lib\site-packages\peft\config.py", line 197, in _get_peft_type
    config_file = hf_hub_download(
  File "C:\Users\admin\.conda\envs\nonebot\lib\site-packages\huggingface_hub\utils\_validators.py", line 111, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\admin\.conda\envs\nonebot\lib\site-packages\huggingface_hub\utils\_validators.py", line 159, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './finetune_demo/output/checkpoint-3000'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\CH\Project\CyberFriend\CyberFriend_LLM_core\api_server.py", line 508, in <module>
    model = PeftModel.from_pretrained(omodel, "./finetune_demo/output/checkpoint-3000")
  File "C:\Users\admin\.conda\envs\nonebot\lib\site-packages\peft\peft_model.py", line 328, in from_pretrained
    PeftConfig._get_peft_type(
  File "C:\Users\admin\.conda\envs\nonebot\lib\site-packages\peft\config.py", line 203, in _get_peft_type
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{model_id}'")
修改为绝对路径并没有解决问题

**Comment by holk-h** [comment]
修改模型路径即可
